import React from 'react';
import './AnimatedBanner.css';

const AnimatedBanner = () => {
    return (
        <div className="banner-container">
            <div className="moving-text">
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
                <span>Discover your next adventure ✨</span>
            </div>
        </div>
    );
};

export default AnimatedBanner;
